### PR TITLE
Add guidance for extension owners on how to update their information

### PR DESCRIPTION
**Pull request by holly-cummins**
I've included (where we can) a link to their actual yaml file, as well as the generic documentation links for this area.

### CODE REVIEW

**Comment by holly-cummins** [comment]
Resolves #71.

**Comment by holly-cummins** [comment]
Hi @maxandersen and @gastaldi, do mind reviewing? I think you can not worry about the changes to `gatsby-node.js`, which are just trying to work out a git path. This is what you'll see in the preview:

image


Here's some examples of different scenarios to look at: 

- https://extensions-quarkus-io-pr-129-preview.surge.sh/io.quarkus/quarkus-kafka-streams - an extension where we don't know its git repo 
- https://extensions-quarkus-io-pr-129-preview.surge.sh/io.quarkiverse.poi/quarkus-poi - an extension where we can link directly to the yaml file 
- https://extensions-quarkus-io-pr-129-preview.surge.sh/io.quarkiverse.pact/quarkus-pact-provider - a multi-extension project where we can still link to the yaml file. It looks exactly the same, but I was pleased to get it working.

**Review by gastaldi — APPROVED** [review]
That's a good idea! 👍🏻

**Comment by maxandersen** [comment]
+1

**Pull request merged**
