### PR TITLE
Show individual contributors in a pie chart

### PR DESCRIPTION
**Pull request by holly-cummins**
Partial resolution of #297.

I've started with showing the individuals, since that won't need an opt-in.

### CODE REVIEW

**Comment by holly-cummins** [comment]
What do you think, @maxandersen and @insectengine? It's worth checking a few different extensions:

- Small contributor count: https://extensions-quarkus-pr-368-preview.surge.sh/io.quarkiverse.pact/quarkus-pact-consumer
- Medium contributor count: https://extensions-quarkus-pr-368-preview.surge.sh/org.optaplanner/optaplanner-quarkus
- Large contributor count: https://extensions-quarkus-pr-368-preview.surge.sh/io.quarkus/quarkus-agroal

I only show labels when there isn't a huge number of contributors, or the lines get too cluttered. The names are visible by hovering, though. 

At the moment it's showing people's GitHub logins, but in a few days after merge it should switch to showing names, as the caches refresh. 

For repos like Quarkus, there are a huge number of contributors. For most extensions in the repo I should be able to use path-specific queries to narrow down the contributor set, but that's kind of an advanced feature, so I haven't done that yet.

**Comment by holly-cummins** [comment]
Suggestions from @maxandersen  - 
- Move the footer with the link to quarkus-extension.yaml to the right column so it doesn't get lost 
- Change the header to 'recent contributors' (at least until I make a one-month and all-time graph)
- Move the contributor information to its own page/tab, and link to it from the front page

**Comment by insectengine** [comment]
From a visual perspective.

1) on the small count, can we make the names black? the issue is the light blue people are hard to read/accessibility issue.
2) on the large count, can we add a column  to the side of the pie with all the contributors listed and their percentages that's always visible?

**Comment by holly-cummins** [comment]
Thanks for the suggestion, @insectengine. I've adjusted the text colour for the label (which was annoyingly hard, but you're right, it was the opposite of accessible as it was), and added a column with contributors for the 'lots' case. I did commit count rather than percentage, since that seemed to be adding more to what was in the pie chart, but let me know if you think percentage is more useful. 

Small number of contributors:

image

Large number of contributors:

image

You're right, it's better this way. WDYT?

Oh, and I swapped the chart to a doughnut chart, since (a) IMO it looks a bit more modern and (b) the internet says it’s easier to interpret.

(I haven't done @maxandersen's suggestions yet)

**Comment by insectengine** [comment]
Looks good!

**Pull request merged**
